import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { Button } from "~/components/ui/button";
import { Download, ImageIcon, AlertCircle, Share } from "lucide-react";
import { Stopwatch } from "./Stopwatch";
import { cn } from "~/lib/utils";
import { imageHelpers } from "~/lib/image-helpers";
import type { ProviderTiming } from "~/lib/image-types";
import { Label } from "~/components/ui/label";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "~/components/ui/tooltip";

interface ImageDisplayProps {
  provider: string;
  image: string | null | undefined;
  timing?: ProviderTiming;
  failed?: boolean;
  fallbackIcon?: React.ReactNode;
  enabled?: boolean;
  modelId: string;
}

export function ImageDisplay({
  provider,
  image,
  timing,
  failed,
  fallbackIcon,
  modelId,
}: ImageDisplayProps) {
  const [isZoomed, setIsZoomed] = useState(false);

  useEffect(() => {
    if (isZoomed) {
      window.history.pushState({ zoomed: true }, "");
    }

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isZoomed) {
        setIsZoomed(false);
      }
    };

    const handlePopState = () => {
      if (isZoomed) {
        setIsZoomed(false);
      }
    };

    if (isZoomed) {
      document.addEventListener("keydown", handleEscape);
      window.addEventListener("popstate", handlePopState);
    }

    return () => {
      document.removeEventListener("keydown", handleEscape);
      window.removeEventListener("popstate", handlePopState);
    };
  }, [isZoomed]);

  const handleImageClick = (e: React.MouseEvent) => {
    if (image) {
      e.stopPropagation();
      setIsZoomed(true);
    }
  };

  const handleActionClick = (
    e: React.MouseEvent,
    imageData: string,
    provider: string,
  ) => {
    e.stopPropagation();
    imageHelpers.shareOrDownload(imageData, provider).catch((error) => {
      console.error("Failed to share/download image:", error);
    });
  };

  return (
    <>
      <div
        className={cn(
          "group relative aspect-square w-full rounded-lg bg-muted",
          image && !failed && "cursor-pointer",
          (!image || failed) && "border border-border",
        )}
        onClick={handleImageClick}
      >
        {(image ?? failed) && (
          <div className="absolute left-2 top-2 flex max-w-[75%] items-center gap-2 rounded-lg border border-border/50 bg-background/95 px-2 py-1 backdrop-blur-sm">
            <TooltipProvider>
              <Tooltip delayDuration={100}>
                <TooltipTrigger asChild>
                  <Label className="min-w-0 grow truncate text-xs text-foreground">
                    {imageHelpers.formatModelId(modelId)}
                  </Label>
                </TooltipTrigger>
                <TooltipContent>
                  <p>{modelId}</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        )}
        {image && !failed ? (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`data:image/png;base64,${image}`}
              alt={`Generated by ${provider}`}
              className="h-full w-full rounded-lg object-cover"
            />
            <Button
              size="icon"
              variant="secondary"
              className="absolute bottom-2 left-2 transition-opacity sm:opacity-0 sm:group-hover:opacity-100"
              onClick={(e) => handleActionClick(e, image, provider)}
            >
              <span className="sm:hidden">
                <Share className="h-4 w-4" />
              </span>
              <span className="hidden sm:block">
                <Download className="h-4 w-4" />
              </span>
            </Button>
            {timing?.elapsed && (
              <div className="absolute bottom-2 right-2 rounded-md bg-black/70 px-2 py-1 shadow backdrop-blur-sm dark:bg-white/10">
                <span className="text-xs font-medium text-white dark:text-white/90">
                  {(timing.elapsed / 1000).toFixed(1)}s
                </span>
              </div>
            )}
          </>
        ) : (
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            {failed ? (
              (fallbackIcon ?? (
                <AlertCircle className="h-8 w-8 text-destructive" />
              ))
            ) : image ? (
              <>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`data:image/png;base64,${image}`}
                  alt={`Generated by ${provider}`}
                  className="h-full w-full rounded-lg object-cover"
                />
                <Button
                  size="icon"
                  variant="secondary"
                  className="absolute bottom-2 left-2 transition-opacity sm:opacity-0 sm:group-hover:opacity-100"
                  onClick={(e) => handleActionClick(e, image, provider)}
                >
                  <span className="sm:hidden">
                    <Share className="h-4 w-4" />
                  </span>
                  <span className="hidden sm:block">
                    <Download className="h-4 w-4" />
                  </span>
                </Button>
              </>
            ) : timing?.startTime ? (
              <>
                <Stopwatch startTime={timing.startTime} />
              </>
            ) : (
              <ImageIcon className="h-12 w-12 text-muted-foreground" />
            )}
          </div>
        )}
      </div>

      {isZoomed &&
        image &&
        createPortal(
          <div
            className="fixed inset-0 z-50 flex min-h-[100dvh] w-screen cursor-pointer items-center justify-center bg-black/90"
            onClick={() => setIsZoomed(false)}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`data:image/png;base64,${image}`}
              alt={`Generated by ${provider}`}
              className="max-h-[90dvh] max-w-[90vw] object-contain"
              onClick={(e) => e.stopPropagation()}
            />
          </div>,
          document.body,
        )}
    </>
  );
}
